container-storage: Don't fail if image media type is not specified
I had this fail for some images like so.

```
Error: failed to open old image: image 33d95258b00dbcec has
unsupported manifest type "", only OCI manifests are supported
```

Turns out media type is optional in the OCI spec.

Signed-off-by: Alexander Larsson <alexl@redhat.com>